### PR TITLE
review: update selectors

### LINKED ISSUE #20: Broken or is it just me?
I'm getting "Error: This pull request is not yet ready to land.  There are no approvals" even when it is approved.

The last issue I tried was: https://github.com/nodejs/abi-stable-node/pull/383

### PR DESCRIPTION
**Pull request by legendecas**
1. Fixes selectors on fetching pull comments
2. Fixes selectors on fetching reviewers

Fixes: #20

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM, seemed to fix for me.

**Comment by mhdawson** [comment]
@evanlucas can this land?

**Comment by evanlucas** [comment]
Fine by me. I have not tested it though. Thanks!

**Comment by mhdawson** [comment]
Ok sicne @evanlucas is ok with it and it seems to work for me will land.

**Pull request merged**
