### PR TITLE
Adding Microsoft Edge compatibility

### PR DESCRIPTION
**Pull request by kfarnung**
Compatibility
* Switched manifest from "activeTab" (which isn't supported in
  Microsoft Edge) to a domain permission for "*://*.github.com/*" which
  covers GitHub and all subdomains.
* Shimmed the "chrome" object for browsers that don't support it
* Switched to scrollIntoView which is compatible with most browsers
* Implemented a message pipe between the content and background
  scripts; connecting to githubusercontent.com violates the CSP in
  Microsoft Edge
* Added Microsoft Edge instructions to the README

Improvements
* Switched to a page action to fix multi-window scenarios
* Detected tab changes using the "onActivated" event
* Enumerated active tabs in all windows on extension load

Cleanup
* Enforced JavaScript Standard Style
* Removed unused "webRequest" permission

edge

chrome

### CODE REVIEW

**Comment by evanlucas** [comment]
Thanks for the contribution. Unfortunately, this doesn't appear to be working on Chrome 60. Here is an example. I sincerely apologize that this has sat unreviewed for such a long time. I'll try to dig into what the problem is this weekend.

screen shot 2017-08-04 at 8 48 09 am

**Comment by kfarnung** [comment]
Thanks for taking a look, I did test on Chrome recently, but not sure which version. I’ll investigate today.

**Comment by kfarnung** [comment]
Interesting, I tried on Windows (Version 60.0.3112.90 (Official Build) (64-bit)) and Mac (Version 60.0.3112.78 (Official Build) beta (64-bit)), but I don't see the issue.

**Comment by kfarnung** [comment]
Hey @evanlucas, I haven't been able to repro that issue on my end, are you still seeing it?

**Comment by gibfahn** [comment]
Does this use the [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) apis? If so it should work on Firefox as well.

**Comment by gibfahn** [comment]
cc/ @tniessen

**Comment by kfarnung** [comment]
I tested it on Firefox at one point and I believe it is compatible. The sideloading process for Firefox wasn't great for anything other than development.

**Comment by gibfahn** [comment]
>I tested it on Firefox at one point and I believe it is compatible. The sideloading process for Firefox wasn't great for anything other than development.

Oh really, what did you try? [web-ext](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext) gives you hot reloading for development, and otherwise you can just load the folder directly in `about:debugging`.

I was trying out webextensions recently and I found the Firefox experience pretty nice (seemed nicer than Chrome for me at least).

If it works we should also get it published to the Chrome/Firefox/Edge stores.

**Comment by kfarnung** [comment]
The main issue was just that it doesn't persist.  It worked fine for development and testing, but for day-to-day usage I needed to jump through hoops to load the local extension.  This may have changed since, I don't use Firefox as my daily driver.

I did test against the latest Firefox beta (57.0b6) and it appears to work fine.  The only warning was this:

> Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

**Comment by Trott** [comment]
OMGlob, this would be amazing. I hope we can get this working and land it. :tada:

**Comment by gibfahn** [comment]
Can confirm that this works on Firefox.

If anyone wants to use it before this PR lands, you can just do:

- Clone the repo
```bash
git clone https://github.com/kfarnung/node-review.git && cd node-review
git checkout edge
```
- go to `about:debugging` in Firefox
- `Enable add-on debugging` and `Load temporary addon`, double-click on the `manifest.json` in `node-review`.
- Go to any node PR
- Success...

image

**Review by gibfahn — APPROVED** [review]

**Comment by evanlucas** [comment]
Thanks!!

**Comment by evanlucas** [comment]
I went ahead and gave you write access. Thanks for sticking with this and sorry for the delay on getting it landed!!

**Pull request merged**
